<?php

namespace App\Http\Requests\Admin\Ejournal;

use Illuminate\Foundation\Http\FormRequest;

class UpdateHomeSettingsRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'home' => ['required', 'array'],

            'home.banner.title' => ['nullable', 'string', 'max:255'],
            'home.banner.typed_strings' => ['nullable', 'string', 'max:500'],
            'home.banner.text' => ['nullable', 'string'],
            'home.banner.button_text' => ['nullable', 'string', 'max:100'],
            'home.banner.button_url' => ['nullable', 'string', 'max:255'],
            'home.banner.image_file' => ['nullable', 'image', 'max:4096'],

            'home.banner.satisfied_partner' => ['nullable', 'array'],
            'home.banner.satisfied_partner.count' => ['nullable', 'integer', 'min:0'],
            'home.banner.satisfied_partner.suffix' => ['nullable', 'string', 'max:20'],
            'home.banner.satisfied_partner.label' => ['nullable', 'string', 'max:120'],
            'home.banner.satisfied_partner.images' => ['nullable', 'array'],
            'home.banner.satisfied_partner.images.*.image_file' => ['nullable', 'image', 'max:4096'],
            'home.banner.satisfied_partner.images.*.image' => ['nullable', 'string', 'max:255'],

            'home.banner.google_rating' => ['nullable', 'array'],
            'home.banner.google_rating.count' => ['nullable', 'integer', 'min:0'],
            'home.banner.google_rating.suffix' => ['nullable', 'string', 'max:50'],
            'home.banner.google_rating.stars' => ['nullable', 'integer', 'min:0', 'max:5'],
            'home.banner.google_rating.image_file' => ['nullable', 'image', 'max:4096'],
            'home.banner.google_rating.image' => ['nullable', 'string', 'max:255'],

            'home.sliding_text_lines' => ['nullable', 'string'],

            'home.about.text' => ['nullable', 'string'],
            'home.about.points_lines' => ['nullable', 'string'],
            'home.about.tagline' => ['nullable', 'string', 'max:120'],
            'home.about.heading_html' => ['nullable', 'string', 'max:2000'],
            'home.about.button_text' => ['nullable', 'string', 'max:120'],
            'home.about.button_url' => ['nullable', 'string', 'max:255'],
            'home.about.office_hours' => ['nullable', 'string', 'max:255'],
            'home.about.phone' => ['nullable', 'string', 'max:60'],

            // About Page (public /about)
            'home.about_page' => ['nullable', 'array'],
            'home.about_page.tagline' => ['nullable', 'string', 'max:120'],
            'home.about_page.heading_html' => ['nullable', 'string', 'max:2500'],
            'home.about_page.text' => ['nullable', 'string'],
            'home.about_page.consultation_button_text' => ['nullable', 'string', 'max:120'],
            'home.about_page.consultation_button_url' => ['nullable', 'string', 'max:255'],
            'home.about_page.office_hours' => ['nullable', 'string', 'max:255'],
            'home.about_page.phone' => ['nullable', 'string', 'max:60'],

            'home.about_page.images' => ['nullable', 'array'],
            'home.about_page.images.*.image_file' => ['nullable', 'image', 'max:4096'],
            'home.about_page.images.*.image' => ['nullable', 'string', 'max:255'],

            'home.about_page.counters' => ['nullable', 'array'],
            'home.about_page.counters.*.count' => ['nullable', 'integer', 'min:0'],
            'home.about_page.counters.*.suffix' => ['nullable', 'string', 'max:10'],
            'home.about_page.counters.*.label' => ['nullable', 'string', 'max:255'],

            'home.about_page.vision' => ['nullable', 'array'],
            'home.about_page.vision.title' => ['nullable', 'string', 'max:120'],
            'home.about_page.vision.subtitle' => ['nullable', 'string', 'max:255'],
            'home.about_page.vision.text' => ['nullable', 'string'],

            'home.about_page.mission' => ['nullable', 'array'],
            'home.about_page.mission.title' => ['nullable', 'string', 'max:120'],
            'home.about_page.mission.subtitle' => ['nullable', 'string', 'max:255'],
            'home.about_page.mission.points_lines' => ['nullable', 'string'],
            'home.about_page.mission.points' => ['nullable', 'array'],
            'home.about_page.mission.points.*.title' => ['nullable', 'string', 'max:255'],
            'home.about_page.mission.points.*.text' => ['nullable', 'string'],

            'home.services.tabs' => ['nullable', 'array'],
            'home.services.tabs.*.button_label' => ['nullable', 'string', 'max:120'],
            'home.services.tabs.*.slug' => ['nullable', 'string', 'max:120'],
            'home.services.tabs.*.icon' => ['nullable', 'string', 'max:120'],
            'home.services.tabs.*.title' => ['nullable', 'string', 'max:255'],
            'home.services.tabs.*.text' => ['nullable', 'string'],
            'home.services.tabs.*.small_label' => ['nullable', 'string', 'max:120'],
            'home.services.tabs.*.small_sublabel' => ['nullable', 'string', 'max:120'],
            'home.services.tabs.*.button_text' => ['nullable', 'string', 'max:120'],
            'home.services.tabs.*.button_url' => ['nullable', 'string', 'max:255'],
            'home.services.tabs.*.image_file' => ['nullable', 'image', 'max:4096'],
            'home.services.tagline' => ['nullable', 'string', 'max:120'],
            'home.services.heading_html' => ['nullable', 'string', 'max:2000'],

            // Services page (additional sections)
            'home.services_page' => ['nullable', 'array'],
            'home.services_page.workflow' => ['nullable', 'array'],
            'home.services_page.workflow.tagline' => ['nullable', 'string', 'max:120'],
            'home.services_page.workflow.heading_html' => ['nullable', 'string', 'max:2500'],
            'home.services_page.workflow.items' => ['nullable', 'array'],
            'home.services_page.workflow.items.*.icon' => ['nullable', 'string', 'max:120'],
            'home.services_page.workflow.items.*.title_html' => ['nullable', 'string', 'max:500'],
            'home.services_page.workflow.items.*.text' => ['nullable', 'string'],
            'home.services_page.workflow.items.*.url' => ['nullable', 'string', 'max:255'],

            'home.services_page.faq' => ['nullable', 'array'],
            'home.services_page.faq.tagline' => ['nullable', 'string', 'max:120'],
            'home.services_page.faq.heading_html' => ['nullable', 'string', 'max:2500'],
            'home.services_page.faq.text' => ['nullable', 'string', 'max:3000'],
            'home.services_page.faq.points_lines' => ['nullable', 'string'],
            'home.services_page.faq.points' => ['nullable', 'array'],
            'home.services_page.faq.points.*' => ['nullable', 'string', 'max:500'],
            'home.services_page.faq.contact' => ['nullable', 'array'],
            'home.services_page.faq.contact.big_text' => ['nullable', 'string', 'max:120'],
            'home.services_page.faq.contact.title_html' => ['nullable', 'string', 'max:1000'],
            'home.services_page.faq.contact.button_text' => ['nullable', 'string', 'max:120'],
            'home.services_page.faq.contact.button_url' => ['nullable', 'string', 'max:255'],
            'home.services_page.faq.accordions' => ['nullable', 'array'],
            'home.services_page.faq.accordions.*.question' => ['nullable', 'string', 'max:255'],
            'home.services_page.faq.accordions.*.answer' => ['nullable', 'string'],

            // Services detail page
            'home.services_detail' => ['nullable', 'array'],
            'home.services_detail.intro_title' => ['nullable', 'string', 'max:2000'],
            'home.services_detail.intro_text' => ['nullable', 'string'],
            'home.services_detail.main_image_file' => ['nullable', 'image', 'max:4096'],
            'home.services_detail.main_image' => ['nullable', 'string', 'max:255'],

            'home.services_detail.highlights_title' => ['nullable', 'string', 'max:255'],
            'home.services_detail.highlights_text' => ['nullable', 'string'],
            'home.services_detail.highlights_left_points_lines' => ['nullable', 'string'],
            'home.services_detail.highlights_left_points' => ['nullable', 'array'],
            'home.services_detail.highlights_left_points.*' => ['nullable', 'string', 'max:255'],
            'home.services_detail.highlights_right_points_lines' => ['nullable', 'string'],
            'home.services_detail.highlights_right_points' => ['nullable', 'array'],
            'home.services_detail.highlights_right_points.*' => ['nullable', 'string', 'max:255'],

            'home.services_detail.cards' => ['nullable', 'array'],
            'home.services_detail.cards.*.icon' => ['nullable', 'string', 'max:120'],
            'home.services_detail.cards.*.title' => ['nullable', 'string', 'max:255'],
            'home.services_detail.cards.*.text' => ['nullable', 'string', 'max:2000'],

            'home.services_detail.workflow_title' => ['nullable', 'string', 'max:255'],
            'home.services_detail.workflow_text' => ['nullable', 'string'],
            'home.services_detail.workflow_image_1_file' => ['nullable', 'image', 'max:4096'],
            'home.services_detail.workflow_image_1' => ['nullable', 'string', 'max:255'],
            'home.services_detail.workflow_image_2_file' => ['nullable', 'image', 'max:4096'],
            'home.services_detail.workflow_image_2' => ['nullable', 'string', 'max:255'],

            'home.services_detail.why_title' => ['nullable', 'string', 'max:255'],
            'home.services_detail.why_text_1' => ['nullable', 'string'],
            'home.services_detail.why_text_2' => ['nullable', 'string'],
            'home.services_detail.why_points_lines' => ['nullable', 'string'],
            'home.services_detail.why_points' => ['nullable', 'array'],
            'home.services_detail.why_points.*' => ['nullable', 'string', 'max:255'],
            'home.services_detail.why_image_file' => ['nullable', 'image', 'max:4096'],
            'home.services_detail.why_image' => ['nullable', 'string', 'max:255'],

            'home.services_detail.post_text' => ['nullable', 'string'],
            'home.services_detail.doi_title' => ['nullable', 'string', 'max:255'],
            'home.services_detail.doi_text' => ['nullable', 'string'],
            'home.services_detail.bottom_image_file' => ['nullable', 'image', 'max:4096'],
            'home.services_detail.bottom_image' => ['nullable', 'string', 'max:255'],

            'home.services_detail.sidebar' => ['nullable', 'array'],
            'home.services_detail.sidebar.more_services_title' => ['nullable', 'string', 'max:255'],
            'home.services_detail.sidebar.more_services_lines' => ['nullable', 'string'],
            'home.services_detail.sidebar.more_services' => ['nullable', 'array'],
            'home.services_detail.sidebar.more_services.*' => ['nullable', 'string', 'max:255'],
            'home.services_detail.sidebar.get_touch_title' => ['nullable', 'string', 'max:255'],
            'home.services_detail.sidebar.button_text' => ['nullable', 'string', 'max:120'],
            'home.services_detail.sidebar.button_url' => ['nullable', 'string', 'max:255'],
            'home.services_detail.sidebar.call_label' => ['nullable', 'string', 'max:255'],
            'home.services_detail.sidebar.phone' => ['nullable', 'string', 'max:60'],

            'home.services_detail.faq' => ['nullable', 'array'],
            'home.services_detail.faq.tagline' => ['nullable', 'string', 'max:120'],
            'home.services_detail.faq.heading_html' => ['nullable', 'string', 'max:2500'],
            'home.services_detail.faq.text' => ['nullable', 'string', 'max:3000'],
            'home.services_detail.faq.points_lines' => ['nullable', 'string'],
            'home.services_detail.faq.points' => ['nullable', 'array'],
            'home.services_detail.faq.points.*' => ['nullable', 'string', 'max:500'],
            'home.services_detail.faq.accordions' => ['nullable', 'array'],
            'home.services_detail.faq.accordions.*.question' => ['nullable', 'string', 'max:255'],
            'home.services_detail.faq.accordions.*.answer' => ['nullable', 'string'],
            'home.services_detail.faq.contact' => ['nullable', 'array'],
            'home.services_detail.faq.contact.big_text' => ['nullable', 'string', 'max:120'],
            'home.services_detail.faq.contact.title_html' => ['nullable', 'string', 'max:1000'],
            'home.services_detail.faq.contact.button_text' => ['nullable', 'string', 'max:120'],
            'home.services_detail.faq.contact.button_url' => ['nullable', 'string', 'max:255'],

            'home.counters' => ['nullable', 'array'],
            'home.counters.*.icon' => ['nullable', 'string', 'max:120'],
            'home.counters.*.count' => ['nullable', 'integer', 'min:0'],
            'home.counters.*.suffixes' => ['nullable', 'string', 'max:50'],
            'home.counters.*.label' => ['nullable', 'string', 'max:255'],

            'home.blog.cards' => ['nullable', 'array'],
            'home.blog.cards.*.day' => ['nullable', 'string', 'max:2'],
            'home.blog.cards.*.month' => ['nullable', 'string', 'max:10'],
            'home.blog.cards.*.tags' => ['nullable', 'string', 'max:500'],
            'home.blog.cards.*.title' => ['nullable', 'string', 'max:255'],
            'home.blog.cards.*.text' => ['nullable', 'string'],
            'home.blog.cards.*.link_url' => ['nullable', 'string', 'max:255'],
            'home.blog.cards.*.image_file' => ['nullable', 'image', 'max:4096'],

            'home.blog.tagline' => ['nullable', 'string', 'max:120'],
            'home.blog.heading_html' => ['nullable', 'string', 'max:2000'],
            'home.blog.button_text' => ['nullable', 'string', 'max:120'],
            'home.blog.button_url' => ['nullable', 'string', 'max:255'],

            // Blog detail page (public /blog-details)
            'home.blog_detail' => ['nullable', 'array'],
            'home.blog_detail.hero' => ['nullable', 'string', 'max:255'],
            'home.blog_detail.hero_file' => ['nullable', 'image', 'max:4096'],
            'home.blog_detail.title' => ['nullable', 'string', 'max:255'],
            'home.blog_detail.author' => ['nullable', 'string', 'max:255'],
            'home.blog_detail.comments' => ['nullable', 'string', 'max:120'],
            'home.blog_detail.published' => ['nullable', 'string', 'max:120'],

            // Blog sidebar (public blog pages)
            'home.blog_sidebar' => ['nullable', 'array'],
            'home.blog_sidebar.search' => ['nullable', 'array'],
            'home.blog_sidebar.search.title' => ['nullable', 'string', 'max:120'],
            'home.blog_sidebar.search.text' => ['nullable', 'string', 'max:255'],
            'home.blog_sidebar.search.placeholder' => ['nullable', 'string', 'max:120'],

            'home.blog_sidebar.categories' => ['nullable', 'array'],
            'home.blog_sidebar.categories.*.slug' => ['nullable', 'string', 'max:120'],
            'home.blog_sidebar.categories.*.label' => ['nullable', 'string', 'max:255'],
            'home.blog_sidebar.categories.*.count' => ['nullable', 'string', 'max:20'],

            'home.blog_sidebar.keywords_lines' => ['nullable', 'string'],
            'home.blog_sidebar.keywords' => ['nullable', 'array'],
            'home.blog_sidebar.keywords.*' => ['nullable', 'string', 'max:120'],

            'home.blog_sidebar.subscribe' => ['nullable', 'array'],
            'home.blog_sidebar.subscribe.title' => ['nullable', 'string', 'max:120'],
            'home.blog_sidebar.subscribe.text' => ['nullable', 'string', 'max:255'],
            'home.blog_sidebar.subscribe.placeholder' => ['nullable', 'string', 'max:120'],
            'home.blog_sidebar.subscribe.button_text' => ['nullable', 'string', 'max:120'],

            'home.contact' => ['nullable', 'array'],
            'home.contact.tagline' => ['nullable', 'string', 'max:120'],
            'home.contact.heading_html' => ['nullable', 'string', 'max:2000'],
            'home.contact.name_placeholder' => ['nullable', 'string', 'max:120'],
            'home.contact.email_placeholder' => ['nullable', 'string', 'max:120'],
            'home.contact.phone_placeholder' => ['nullable', 'string', 'max:120'],
            'home.contact.subject_placeholder' => ['nullable', 'string', 'max:120'],
            'home.contact.subject_options_lines' => ['nullable', 'string'],
            'home.contact.message_placeholder' => ['nullable', 'string', 'max:255'],
            'home.contact.button_text' => ['nullable', 'string', 'max:120'],
            'home.contact.image_main_file' => ['nullable', 'image', 'max:4096'],
            'home.contact.image_small1_file' => ['nullable', 'image', 'max:4096'],
            'home.contact.image_small2_file' => ['nullable', 'image', 'max:4096'],
            'home.contact.image_main' => ['nullable', 'string', 'max:255'],
            'home.contact.image_small1' => ['nullable', 'string', 'max:255'],
            'home.contact.image_small2' => ['nullable', 'string', 'max:255'],

            // Contact page (public /contact)
            'home.contact_page' => ['nullable', 'array'],
            'home.contact_page.left_tagline' => ['nullable', 'string', 'max:120'],
            'home.contact_page.left_title_html' => ['nullable', 'string', 'max:2000'],
            'home.contact_page.left_text' => ['nullable', 'string', 'max:255'],
            'home.contact_page.address_title' => ['nullable', 'string', 'max:120'],
            'home.contact_page.address_html' => ['nullable', 'string', 'max:500'],
            'home.contact_page.contact_info_title' => ['nullable', 'string', 'max:120'],
            'home.contact_page.phone' => ['nullable', 'string', 'max:60'],
            'home.contact_page.email' => ['nullable', 'string', 'max:120'],
            'home.contact_page.working_time_title' => ['nullable', 'string', 'max:120'],
            'home.contact_page.time_label' => ['nullable', 'string', 'max:60'],
            'home.contact_page.time_value' => ['nullable', 'string', 'max:120'],
            'home.contact_page.days_label' => ['nullable', 'string', 'max:60'],
            'home.contact_page.days_value' => ['nullable', 'string', 'max:120'],
            'home.contact_page.right_tagline' => ['nullable', 'string', 'max:120'],
            'home.contact_page.right_title' => ['nullable', 'string', 'max:120'],

            'home.manuscript' => ['nullable', 'array'],
            'home.manuscript.title' => ['nullable', 'string', 'max:120'],
            'home.manuscript.subtitle' => ['nullable', 'string', 'max:255'],
            'home.manuscript.name_placeholder' => ['nullable', 'string', 'max:120'],
            'home.manuscript.email_placeholder' => ['nullable', 'string', 'max:120'],
            'home.manuscript.phone_placeholder' => ['nullable', 'string', 'max:120'],
            'home.manuscript.category_placeholder' => ['nullable', 'string', 'max:120'],
            'home.manuscript.category_options_lines' => ['nullable', 'string'],
            'home.manuscript.button_text' => ['nullable', 'string', 'max:120'],

            'home.testimonials' => ['nullable', 'array'],
            'home.testimonials.tagline' => ['nullable', 'string', 'max:120'],
            'home.testimonials.heading_html' => ['nullable', 'string', 'max:2000'],
            'home.testimonials.items' => ['nullable', 'array'],
            'home.testimonials.items.*.name' => ['nullable', 'string', 'max:120'],
            'home.testimonials.items.*.role' => ['nullable', 'string', 'max:120'],
            'home.testimonials.items.*.sub_title' => ['nullable', 'string', 'max:255'],
            'home.testimonials.items.*.text' => ['nullable', 'string', 'max:2000'],
            'home.testimonials.items.*.date' => ['nullable', 'string', 'max:60'],
            'home.testimonials.items.*.rating' => ['nullable', 'integer', 'min:0', 'max:5'],
            'home.testimonials.items.*.link_url' => ['nullable', 'string', 'max:255'],
            'home.testimonials.items.*.image_file' => ['nullable', 'image', 'max:4096'],
            'home.testimonials.items.*.image' => ['nullable', 'string', 'max:255'],
        ];
    }
}
